 
// program_list.h autogenerated 
#ifndef _PROGRAM_LIST_H_ 
#define _PROGRAM_LIST_H_ 
 
// include the lib of programs format 
#include "program_lt.h"  
 
// include your programs 
#include "../programs/Example1.h" 
 
// include your program functionallity to the list 
ThridyParterProgram ProgramsList[] = { 
   { L"Hello World" , Example1 }, 
   	{ NULL , NULL } 
}; 
#endif // _PROGRAM_LIST_H_ 
