@echo off

@REM moontool.bat

@REM abstract:
@REM    build the programs in msvc/programs, si , esto the hace la tarea xddddd

setlocal enabledelayedexpansion

@REM avoid errors
pushd
cd %~dp0

goto ParseArgs

:ParseArgs
if /I "%1"=="-h" goto usage
if /I "%1"=="-help" goto usage
if /I "%1"=="-bprograms" goto build
if /I "%1"=="-bprg" goto build
goto usage

:usage
    echo MoonTool
    echo.
    echo abstract:
    echo    a ofitial by ErickCraftStudios tool for help to the developers of S-SUN mods for complement the compilation for the system
    echo    (yes now you dont need thridy party tools for compile a custom S-SUN installation)
    echo.
    echo profesional use:
    echo    this tool can be used for the oem personal for add "bloatware" (ohhh , i... say utilities) ... yeah , utilities by default
    echo.
    echo Usage:
    echo    -bprograms: build the programs
    echo    -bprg: -bprograms
    echo    -h: help
    echo    -help: -h
    echo.
    echo Second Param options:
    echo    -oem_st: specially for oem vendors
    echo. 

    goto end

:build

if /I "%2"=="-oem_st" (
    echo "welcome to S-SUN world, oem vendor ^-^"
    set /P oem_vendor=Please put the name of your vendor:  
    set /P oem_time=Please put the year when the vendor has been created:  

    if not defined oem_time (
        echo ERROR: Year cannot be empty!
        goto end
    )
)

@REM enter in programs folder
cd programs

echo. > ../sources/program_list.h

if /I "%2"=="-oem_st" (
    echo /*+++ >> ../sources/program_list.h
    echo. >> ../sources/program_list.h
    echo Copyright !oem_time! !oem_vendor! >> ../sources/program_list.h
    echo. >> ../sources/program_list.h

    echo abstract: >> ./sources/program_list.h
    echo    add the OEM vendor utilities to S-SUN >> ../sources/program_list.h
    echo. >> ../sources/program_list.h
    echo ---*/ >> ../sources/program_list.h
    echo. >> ../sources/program_list.h
)

@REM write the file
echo // program_list.h autogenerated >> ../sources/program_list.h

@REM write the guard
echo #ifndef _PROGRAM_LIST_H_ >> ../sources/program_list.h
echo #define _PROGRAM_LIST_H_ >> ../sources/program_list.h

@REM write a void space to make it more normally
echo. >> ../sources/program_list.h

echo // include the lib of programs format >> ../sources/program_list.h
echo #include "program_lt.h"  >> ../sources/program_list.h
echo. >> ../sources/program_list.h

echo // include your programs >> ../sources/program_list.h

@REM include the programs
for %%F in (*.h) do (
    echo adding file: %%F

    echo #include "../programs/%%F" >> ../sources/program_list.h
)

@REM write void spaces
echo. >> ../sources/program_list.h

@REM write the indicator
echo // include your program functionallity to the list >> ../sources/program_list.h

@REM write the declarator
echo ThridyParterProgram ProgramsList[] = { >> ../sources/program_list.h

@REM add your programs
for %%F in (*.h) do (

    set "Label="
    set "function="
    set "counter=0"
    set "excluded=0"

    echo information of file: %%F

    for /F "delims=" %%A in (%%F) do (
        set /a counter+=1
        if !counter! EQU 2 (
            set "xd=%%A"
            if !xd! EQU "@EXCLUDE"  (
                set "excluded=1"
            )
        )
        if !counter! EQU 4 set "Label=%%A"
        if !counter! EQU 5 set "function=%%A"
    )

        echo creating display name as : !Label!
        echo creating function name as : !function!

        echo    { L"!Label!" , !function! }, >> ../sources/program_list.h
    )
)

@REM add the terminator
echo    	{ NULL , NULL } >> ../sources/program_list.h
echo }; >> ../sources/program_list.h

@REM add the end of the header
echo #endif // !_PROGRAM_LIST_H_ >> ../sources/program_list.h
goto end

:end
if /I "%2" NEQ "-fvs" (
pause
)
popd

endlocal
